update to 2.0.2
This doesn't build for me yet.

/usr/include/jpeglib.h:1000:30: error: unknown type name 'FILE'
 EXTERN(void) jpeg_stdio_dest JPP((j_compress_ptr cinfo, FILE * outfile));

git-svn-id: file:///srv/repos/svn-community/svn@95797 9fca08f4-af9d-4005-b8df-a31f2cc04f65